// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/10/2025 23:06:36
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/moham/Documents/chamseddine/Projet/chems khalid saadaqa/Sadaqa-Jariya/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/moham/Documents/chamseddine/Projet/chems khalid saadaqa/Sadaqa-Jariya/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/moham/Documents/chamseddine/Projet/chems khalid saadaqa/Sadaqa-Jariya/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/moham/Documents/chamseddine/Projet/chems khalid saadaqa/Sadaqa-Jariya/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/moham/Documents/chamseddine/Projet/chems khalid saadaqa/Sadaqa-Jariya/app/plugins/**/*.{js,ts,mjs}","C:/Users/moham/Documents/chamseddine/Projet/chems khalid saadaqa/Sadaqa-Jariya/app/composables/**/*.{js,ts,mjs}","C:/Users/moham/Documents/chamseddine/Projet/chems khalid saadaqa/Sadaqa-Jariya/app/utils/**/*.{js,ts,mjs}","C:/Users/moham/Documents/chamseddine/Projet/chems khalid saadaqa/Sadaqa-Jariya/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/moham/Documents/chamseddine/Projet/chems khalid saadaqa/Sadaqa-Jariya/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/moham/Documents/chamseddine/Projet/chems khalid saadaqa/Sadaqa-Jariya/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/moham/Documents/chamseddine/Projet/chems khalid saadaqa/Sadaqa-Jariya/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;