// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/10/2025 21:36:07
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/kharrari01/Documents/Sadaqa-Jariya/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/kharrari01/Documents/Sadaqa-Jariya/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/kharrari01/Documents/Sadaqa-Jariya/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/kharrari01/Documents/Sadaqa-Jariya/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/kharrari01/Documents/Sadaqa-Jariya/app/plugins/**/*.{js,ts,mjs}","/home/kharrari01/Documents/Sadaqa-Jariya/app/composables/**/*.{js,ts,mjs}","/home/kharrari01/Documents/Sadaqa-Jariya/app/utils/**/*.{js,ts,mjs}","/home/kharrari01/Documents/Sadaqa-Jariya/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/kharrari01/Documents/Sadaqa-Jariya/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/kharrari01/Documents/Sadaqa-Jariya/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;